add hw_1
nico-nico13/NikitaSkrebov pull request #2
Opened 2022-02-18 11:54 UTC by nico-nico13

2022-02-21 13:25 UTC, akulebyakin requested changes
Please review comments

2022-02-21 13:25 UTC, akulebyakin commented on src/test/java/com/epam/tc/hw1/DivideTest.java
> +    public void testDivide(int a, int b, int expected) {
Let's add some test that will check division by 0

2022-02-21 13:25 UTC, akulebyakin commented on src/test/resources/AddSubtract.xml
> +    <test verbose="2" preserve-order="true" name="C:\Users\EVA Unit-11\Desktop\EPAM\selenium\HW1. Unit Frameworks\HW1">
Why such a strange name for a test?
`name="C:\Users\EVA Unit-11\Desktop\EPAM\selenium\HW1. Unit Frameworks\HW1"`

2022-02-22 19:31 UTC, nico-nico13 commented
@akulebyakin Добавил отдельный тест на деление на ноль

2022-02-27 00:14 UTC, akulebyakin approved these changes
approved

2022-03-05 10:59 UTC, merged